version: '2.2'
services:
  mysql:
    image: mysql:5.7.27
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config:/etc/mysql/mysql.conf.d
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
